# Generated by Django 3.1.7 on 2021-03-29 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('ansid', models.AutoField(primary_key=True, serialize=False, verbose_name='评论Id')),
                ('queid', models.IntegerField(verbose_name='被评论问题id')),
                ('userid', models.IntegerField(verbose_name='评论者id')),
                ('content', models.TextField(max_length=3000, verbose_name='评论内容')),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 3, 29, 20, 16, 48, 425990), verbose_name='评论时间')),
            ],
            options={
                'db_table': 'Answer',
            },
        ),
        migrations.CreateModel(
            name='HotNews',
            fields=[
                ('newsid', models.AutoField(primary_key=True, serialize=False, verbose_name='新闻Id')),
                ('content', models.TextField(max_length=3000, verbose_name='内容')),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 3, 29, 20, 16, 48, 425990), verbose_name='发布时间')),
                ('imageUrl', models.CharField(max_length=100, verbose_name='插图')),
                ('tag', models.SmallIntegerField(choices=[(0, '待定'), (1, '真'), (2, '假')], verbose_name='真假')),
            ],
            options={
                'db_table': 'HotNews',
            },
        ),
        migrations.CreateModel(
            name='MyLike',
            fields=[
                ('likeid', models.AutoField(primary_key=True, serialize=False, verbose_name='收藏条目id')),
                ('userid', models.IntegerField(verbose_name='收藏者id')),
                ('newsid', models.IntegerField(verbose_name='被收藏新闻id')),
            ],
            options={
                'db_table': 'MyLike',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('queid', models.AutoField(primary_key=True, serialize=False, verbose_name='问题Id')),
                ('userid', models.IntegerField(verbose_name='提问用户id')),
                ('content', models.TextField(max_length=300, verbose_name='内容')),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 3, 29, 20, 16, 48, 425990), verbose_name='提问时间')),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False, verbose_name='用户Id')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('nickname', models.CharField(max_length=20, verbose_name='昵称')),
                ('iconUrl', models.CharField(max_length=100, verbose_name='头像Url')),
                ('tel', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
