# Generated by Django 3.1.7 on 2021-03-29 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_auto_20210329_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 23, 57, 1, 959094), verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='tag',
            field=models.SmallIntegerField(choices=[(0, '待定'), (1, '真'), (2, '假')], default=0, verbose_name='真假'),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 23, 57, 1, 959094), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 23, 57, 1, 959094), verbose_name='提问时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='iconUrl',
            field=models.CharField(blank=True, max_length=100, verbose_name='头像Url'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
