# Generated by Django 3.1.7 on 2021-04-02 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0009_auto_20210330_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 20, 53, 10, 530634), verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 20, 53, 10, 530634), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 20, 53, 10, 530634), verbose_name='提问时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='iconUrl',
            field=models.CharField(blank=True, default='/static/picture/testimg.jpg', max_length=255, null=True, verbose_name='头像Url'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ticket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='用户名'),
        ),
    ]
