# Generated by Django 3.1.7 on 2021-04-09 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0012_auto_20210407_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='favor',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='answer',
            name='replyid',
            field=models.IntegerField(blank=True, null=True, verbose_name='回复id'),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default=0, max_length=250, verbose_name='问题标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='queid',
            field=models.IntegerField(verbose_name='问题id'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 17, 58, 53, 608797), verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='imageUrl',
            field=models.CharField(max_length=250, verbose_name='插图'),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 17, 58, 53, 607800), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 17, 58, 53, 607800), verbose_name='提问时间'),
        ),
    ]
