# Generated by Django 3.1.7 on 2021-04-09 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0013_auto_20210409_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ansid',
            new_name='answerid',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='queid',
            new_name='questionid',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='queid',
            new_name='questionid',
        ),
        migrations.AlterField(
            model_name='answer',
            name='replyid',
            field=models.IntegerField(default=0, verbose_name='回复id'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 19, 9, 9, 320095), verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 19, 9, 9, 319097), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 19, 9, 9, 320095), verbose_name='提问时间'),
        ),
    ]
