# Generated by Django 3.1.7 on 2021-04-09 16:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0014_auto_20210409_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 0, 25, 57, 995436), verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 0, 25, 57, 994393), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 0, 25, 57, 994393), verbose_name='提问时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.user', verbose_name='提问者Id'),
        ),
    ]
