# Generated by Django 3.1.7 on 2021-04-10 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0015_auto_20210410_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerid', models.IntegerField(verbose_name='被点赞的回答id')),
                ('userid', models.IntegerField(verbose_name='点赞用户id')),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 4, 10, 21, 42, 3, 841279), verbose_name='操作时间')),
            ],
            options={
                'db_table': 'AnswerLike',
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 21, 42, 3, 825658), verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='hotnews',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 21, 42, 3, 825658), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 21, 42, 3, 825658), verbose_name='提问时间'),
        ),
    ]
